export type Person = {
  id: number;
  firstName: string;
  lastName: string;
  fullName: string;
  nif: string;
  niss: string;
  address: string;
  birthDate: string;
  email: string;
  gender: string;
  habilitation: string;
  iban: string;
  identificationNumber: string;
  identificationValidationDate: string;
  identificationType: string;
  nationality: string;
  naturality: string;
  phoneNumber: string;
  zipCode: string;
  age: number;
};
