// icons.ts
import {
  faCheckCircle,
  faLink,
  faMailBulk,
  faPen,
  faExclamationTriangle,
  faCircleInfo,
  faUser,
  faClipboard,
  faAdd,
  faBriefcase,
  faSearch,
  faSignal,
  faX,
  faGraduationCap,
  faGlobe,
  faCalendar,
} from '@fortawesome/free-solid-svg-icons';

export const ICONS = {
  link: faLink,
  email: faMailBulk,
  success: faCheckCircle,
  fail: faX,
  edit: faPen,
  delete: faExclamationTriangle,
  detail: faCircleInfo,
  add: faAdd,
  user: faUser,
  clipboard: faClipboard,
  briefcase: faBriefcase,
  search: faSearch,
  habilitation: faGraduationCap,
  signal: faSignal,
  globe: faGlobe,
  calendar: faCalendar,
};
